- Gemfile.lock
- lib/aha-services/version.rb
- lib/services/jira.rb
> Send due date to jira

- lib/services/trello.rb
Responds to the following support tickets:
https://ahasupport.zendesk.com/agent/#/tickets/36156
https://ahasupport.zendesk.com/agent/tickets/36063
> Add fixes for Trello timestamps and HTML Escaping

- lib/aha-services/version.rb
- lib/services/rally.rb
- lib/services/rally/rally_attachment_content_resource.rb
- lib/services/rally/rally_attachment_resource.rb
- lib/services/rally/rally_hierarchical_requirement_resource.rb
- lib/services/rally/rally_portfolio_item_resource.rb
- lib/services/rally/rally_project_resource.rb
- lib/services/rally/rally_release_resource.rb
- lib/services/rally/rally_resource.rb
- lib/services/rally/rally_state_resource.rb
- lib/services/rally/rally_workspace_resource.rb
- lib/services/rally/webhook.rb
Allow users to change the rally workspace in which the integration will create items.
> App 2129 rally workspaces

- lib/aha-services/version.rb
- lib/services/tfs/tfs_feature_mapping_resource.rb
- lib/services/tfs/tfs_requirement_mapping_resource.rb
Can I please get a sanity check on this. Is for a support ticket
> Correctly handle moving a requirements between features

- lib/services/jira.rb
- spec/services/jira_spec.rb
These changes are just to try and fix some of the jira related tests which I found were broken when running the rspec tests. There are no real code changes (other then formatting) just changes to some of the tests.
> Fix broken jira tests

- lib/aha-services/version.rb
- lib/services/jira/jira_mapped_fields.rb
- lib/services/jira/jira_user_resource.rb
> App 2911 jira custom field

- docs/tfs.md
- lib/aha-services/version.rb
https://big.aha.io/features/APP-3313
> APP-3313: Update the TFS docs to latest

- docs/tfs.md
- lib/aha-services/version.rb
This came in last night as well. Related to #85
> APP-3313: Update more TFS docs

- Gemfile.lock
- lib/aha-services/version.rb
- lib/services/github_issues.rb
- lib/services/gitlab_issues.rb
- spec/services/github_issues_spec.rb
- spec/services/gitlab_issues_spec.rb
Fine day to add some issues. It's best if the github issues know where
they come from. Knowing there roots will help them expand and move
forward in their issue life cycle.
Added url if resource has url
Updated specs
Updated minor version
Becker
> Add link back to aha

- lib/aha-services/version.rb
- lib/services/fogbugz/fogbugz_resource.rb
- spec/services/fogbugz/fogbugz_resource_spec.rb
URI.join cuts off subdirectories if they do not end in a slash
> APP-3913 Use File.join instead of URI.join

- lib/aha-services/version.rb
- lib/services/github_issues.rb
- spec/services/github_issues_spec.rb
https://big.aha.io/features/APP-4053
> APP-4053 Update milestone upon updating feature with differing release

- lib/aha-services/version.rb
- lib/services/slack.rb
> Handle misconfigured slack integrations

- docs/jira.md
- lib/aha-services/version.rb
A small change can mean the world to a confused developer trying to
figure out how to set aha up for there boss. Let us leave a clear
path for that poor soul.
Changes:
Update text to reflect the correct number.
Becker
Addresses https://big.aha.io/features/APP-4611
> APP-4611 Update jira text

- lib/aha-services/version.rb
- lib/services/jira.rb
> Fix typo in JIRA settings

- Gemfile.lock
- lib/aha-services/version.rb
- lib/services/rally/rally_webhook_resource.rb
Rally has decided to change their webhooks API endpoint. Updating to fix our integration.
> APP-4823: Change to new Rally webhooks URL.

- lib/aha-services/version.rb
- lib/services/salesforce.rb
I missed the blank check for the install button.
> Handle a blank host on install as well

- docs/gitlab_issues.md
- lib/aha-services/version.rb
They moved it to it's own doc.
> Update GitLab documentation link

- lib/aha-services/version.rb
- lib/services/jira/jira_mapped_fields.rb
https://sentry.io/aha-labs-inc/aha-production/issues/330834208/
Fixes AHA-PRODUCTION-MD3
> Raise error on invalid configuration of array field to number

- lib/aha-services/version.rb
- lib/services/pivotal_tracker/pivotal_tracker_resource.rb
https://sentry.io/aha-labs-inc/aha-production/issues/330978810/
Fixes AHA-PRODUCTION-MDD
> Require api token for pivotal tracker

- docs/jira.md
- docs/jira_connect.md
- lib/aha-services/service.rb
- lib/aha-services/version.rb
- lib/services/audit_webhook.rb
- lib/services/desk_dot_com.rb
- lib/services/development_proxy.rb
- lib/services/flowdock.rb
- lib/services/hip_chat.rb
- lib/services/jira.rb
- lib/services/jira_connect.rb
- lib/services/salesforce.rb
- lib/services/slack.rb
- lib/services/webhooks.rb
- lib/services/zendesk.rb
https://big.aha.io/features/PM-50
Put each integration into a category in the UI.
Renamed JIRA to Jira to match new Atlassian branding.
> PM-50 integration categories

- lib/aha-services/version.rb
- lib/services/github_issues.rb
https://big.aha.io/features/APP-5928
> Fix sending nil tags over to github

- .ruby-gemset
Remove gemset file, it creates more problems than it is worth
> APP-6259: Remove gemset

- docs/slack_commands.md
- lib/aha-services/schema.rb
- lib/aha-services/version.rb
- lib/services/slack.rb
- lib/services/slack_commands.rb
This is related to [this Aha! feature](https://big.aha.io/features/APP-4255) and should be merged at the same time.
> App 4255 new slack service

- docs/bitbucket_issues.md
- docs/bugzilla.md
- docs/fogbugz.md
- docs/github_issues.md
- docs/gitlab_issues.md
- docs/jira.md
- docs/pivotal_tracker.md
- docs/rally.md
- docs/redmine.md
- docs/tfs.md
- docs/tfs_on_premise.md
- docs/trello.md
- docs/webhooks.md
This updates the copy for our new UI. There will be a related PR to update the gemfile in aha-app.
> Update instructions copy for universal headers

- lib/services/desk_dot_com.rb
https://big.aha.io/requirements/APP-6641-18
> APP-6641-18: Sentence case the install button for Desk.com

- Gemfile.lock
https://nvd.nist.gov/vuln/detail/CVE-2017-18258
https://groups.google.com/forum/#!topic/nokogiri-talk/3dRsQfJIhE8
https://big.aha.io/features/APP-7120
> APP-7120 Upgrade of nokogiri for security 

- lib/aha-services/version.rb
- lib/services/github_issues.rb
https://big.aha.io/features/APP-7119
> App 7119 Add message when issue is not linked to Aha! during github webhook

- lib/aha-services/version.rb
- lib/services/gitlab_issues.rb
Bump version and update description
> APP-7432: GitLab update release

- lib/aha-services/version.rb
- lib/services/gitlab/gitlab_repo_resource.rb
Also restrict to projects that use issues
https://big.aha.io/features/APP-7716
> App 7716 filter projects by member not owner

- lib/services/rally/rally_attachment_content_resource.rb
- lib/services/rally/rally_attachment_resource.rb
- lib/services/rally/rally_release_resource.rb
Updates to rally endpoint
https://big.aha.io/features/RDMPE-54
> RDMPE-54-rally-endpoint

- Gemfile
- lib/services/jira.rb
- lib/services/jira/jira_wiki_converter.rb
- spec/services/github_issues_spec.rb
- spec/services/gitlab_issues_spec.rb
- spec/services/jira/jira_wiki_converter_spec.rb
Explanation here: https://github.com/aha-app/aha-app/pull/7041
Please merge and deploy at the same time as https://github.com/aha-app/aha-services-2/pull/543
> PM 491 new jira wiki converter

- lib/services/generic_resource.rb
Add in a User Agent.
Changes
Add User-Agent to header
Becker
> PF-133-add-user-agent

- docs/tfs.md
- docs/tfs_on_premise.md
- lib/services/tfs.rb
- lib/services/tfs/tfs_common.rb
- lib/services/tfs/tfs_resource.rb
- lib/services/vso.rb
* TFS -> Azure DevOps Server
* VSTS -> Azure DevOps Services
* Fix some typos
> PM-484 Update Microsoft TFS/VSTS branding

- docs/microsoft_teams.md
- lib/services/microsoft_teams.rb
Adds teams integration to Aha!
> Pm 608 ms teams

- lib/services/jira/jira_project_resource.rb
- spec/services/jira/project_resource_spec.rb
Jira Cloud API is removing `/project` (unpaginated) in favor of `/project/search` (paginated), but `/project/search` is not available for all on-prem Jira instances, so we have to fall back to the unpaginated endpoint.
> PF-316-1: Fall back to unpaginated project API endpoint for Jira on-prem

- lib/aha-services/service.rb
- lib/aha-services/version.rb
Dearest reviewer,
Given this is ruby there is no guarantee that another class will not add
itself to the list of ancestors. Moving to a static list that will be
hand updated.
Becker
> PF-473-1-static-list-of-classes

- docs/security_webhook.md
- lib/aha-services/service.rb
- lib/services/security_webhook.rb
Add a webhook for sending security specific information.
> Apps 277 security activity webhooks

- docs/confluence.md
- lib/aha-services/schema.rb
- lib/aha-services/service.rb
- lib/services/confluence.rb
Add confluence to list of services
[Ships with aha-app](https://github.com/aha-app/aha-app/pull/9972)
> PM-780 Confluence Integration

- lib/services/pivotal_tracker.rb
Receive pivotal "epic" updates
> PF-833: Receive epic webhooks from pivotal tracker

- lib/services/jira/jira_mapped_fields.rb
> USB-892 Handle Rails 5 args

- docs/fogbugz.md
- lib/services/fogbugz.rb
Update copy for fogbugz integration settings
> A-10212: Broken link on Fogbugz integration settings

- lib/services/microsoft_teams.rb
- spec/lib/services/microsoft_teams_spec.rb
- spec/spec_helper.rb
Handle non JSON errors from TFS
Fixes AHA-PRODUCTION-5YS7
> USB-1021 Handle non JSON error

- docs/slack_commands.md
> Change master terminology for slack

- docs/microsoft_teams.md
> Update Microsoft Teams docs

- lib/aha-services/version.rb
- lib/services/slack.rb
- spec/services/slack_spec.rb
https://big.aha.io/features/CN-884
Fixes https://sentry.io/organizations/aha-labs-inc/issues/1715462397
> Fixes CN-884 - Handle invalid JSON being returned by Slack.

- docs/github_commit_hook.md
> DEVELOP-753: Text change on GitHub Commit Hook installation instructions

- lib/aha-services.rb
- lib/aha-services/networking/networking.rb
- lib/aha-services/networking/verify_net_adapter.rb
- lib/net_http_persistent_override.rb
overridable net::http adapters
> Devops 1125 http adapters

- docs/confluence.md
- docs/fogbugz.md
- docs/jira.md
- docs/salesforce.md
- lib/services/fogbugz.rb
> A-14262: Confluence integration set up has outdated link

- Gemfile
- Gemfile.lock
- aha-services.gemspec
- lib/aha-services.rb
- lib/aha-services/networking/networking.rb
- lib/services/github/github_resource.rb
- lib/services/jira/jira_resource.rb
- lib/services/rally/rally_resource.rb
- lib/services/tfs/tfs_resource.rb
See main aha-app PR for details: https://github.com/aha-app/aha-app/pull/27002.
> DEVOPS-1952: update faraday

- Gemfile
- Gemfile.lock
- aha-services.gemspec
- lib/aha-services/networking/networking.rb
See main PR for description: https://github.com/aha-app/aha-app/pull/27164
> DEVOPS-1952: replace custom gzip faraday middleware with gem
