aha-app/aha-services

- lib/aha-services/version.rb
- lib/services/jira/jira_project_resource.rb
Prevents timeouts when working with slow servers, or servers with many projects.
> Call createmeta separately for each project.

- lib/aha-services/version.rb
- lib/services/trello.rb
The `feature/release/parking_lot` field isn't yet emitted by the API in this context, but it will be shortly. In the meantime, `Hashie::Mash` ensures it will behave as it used to by returning `nil`.
> Don't create cards with due dates when release is in parking lot.

- lib/services/tfs/tfs_feature_mapping_resource.rb
I just added a simple sync for the VSTS service so original_estimate in Aha can be updated in VSTS's effort field and vice-versa.
It's useful for us in order to push releases to teams using VSTS without having to manually update the effort field of each feature.
> Added estimates <-> effort sync for VSTS service

- Gemfile
- lib/aha-services/service.rb
- lib/aha-services/version.rb
- lib/services/generic_resource.rb
- lib/services/rally.rb
- lib/services/rally/rally_hierarchical_requirement_resource.rb
- lib/services/rally/rally_portfolio_item_resource.rb
- lib/services/trello.rb
- spec/services/github_issues_spec.rb
- spec/services/jira_connect_spec.rb
- spec/services/jira_spec.rb
- spec/services/rally_spec.rb
- spec/services/tfs_spec.rb
WIP
----
Rally may be configured with custom fields which are mandatory. Aha! should support populating these fields when creating stories or portfolio items in Rally.
This should be implemented using the same technique as TFS.
> App 2231 rally custom fields

- docs/github_issues.md
- lib/aha-services/version.rb
- lib/services/github_issues.rb
- spec/services/github_issues_spec.rb
Resolves [APP-I-1485](https://big.ideas.aha.io/ideas/APP-I-1485)
Modifies the existing `github_issues` integration to add support for syncing the aha state to a github label. This feature can be enabled or disabled based on the added checkbox to the configuration called "Add status labels" (As shown in screenshot of the form below)
When the feature has been sent to github issues then a label is added to the issue with a prefix/namespace of "aha:". This namespace allows for the plugin to distinguish between status/state changes and regular tags. Only one github label with the prefix "aha:" is allowed when the feature is enabled.
Changing the label in the corresponding github issue also causes the state of the feature in aha to be updated as well.
14 new tests have been added to test the …
> Add labels syncing with github issues

- lib/services/pivotal_tracker/pivotal_tracker_project_dependent_resource.rb
- spec/services/pivotal_tracker/pivotal_tracker_project_dependent_resource_spec.rb
Not a big fan of this type of unit test (reaching out to protected method), but there's
not another easy way to get at it.
> APP-3061: Don't append the requirement description in PT if it already is present

- lib/services/rally/rally_hierarchical_requirement_resource.rb
Rally will throw an error and reject updates if a release id is passed along to an update of a non-leaf-node user story
> App 3186 update rally user story with children

- lib/services/slack.rb
> Slack Descriptions should be full-width attachment fields.

- lib/aha-services/version.rb
- lib/services/bitbucket_commit_hook.rb
https://big.aha.io/features/APP-3507
https://sentry.io/aha-labs-inc/aha-production/issues/220276760/
We're getting some payloads where the "commit" element for "commits" are nil.
This makes it so we're a little more explicit with the coercion and more forgiving
in what's handled without error.
Specifically we were get `message undefined` errors on the `commit.message` call within
the commits loop below this change:
```ruby
commits = (commit_payload.push.changes.flat_map(&:commits) rescue []) || []
commits.each do |commit|
->  commit.message.scan(/([A-Z]+-[0-9]+(?:-[0-9]+)?)/) do |m|
m.each do |ref|
comment_on_record(ref, commit)
end
```
> APP-3507: Gracefully handle unexpected bitbucket payloads

- lib/services/jira.rb
Some `NoMethodErrors` on `nils` have been getting through when we could be proactively bubbling up a more useful error message to the integration configurer.
See: [ticket](https://ahasupport.zendesk.com/agent/tickets/104538), [rollbar](https://rollbar.com/Aha/prod1/items/30171/occurrences/21880538139/), [feature](https://big.aha.io/features/APP-3485)
Just looking for approval on this PR, I'll manually craft a merge commit that also bumps the version once approved.
> Handle more edge cases in configuration.

- lib/aha-services/version.rb
- lib/services/github_issues.rb
- lib/services/gitlab_issues.rb
Previously we were using the `feature` attribute, but it could be a `requirement` if requirement <-> issue mapping is enabled.
> APP-3561: Use `resource_kind` when sending status labels back to GitHub/Lab.

- lib/aha-services/version.rb
- lib/services/jira.rb
Only send all of the requirements for a feature when initially creating it.
The requirement updates will be sent using the requirement specific events.
This solves a problem where updating a field in a feature with a large number of requirements triggered a huge amount of update activity as each requirement was updated.
> When updating a feature to JIRA do not update all requirements.

- lib/services/trello.rb
- spec/services/trello_spec.rb
Please see internal feature for further details
Trello changed its attachment file name normalization. This updates our implementation to match their normalization so that we don't duplicate attachments
> normalizing filenames for trello

- lib/aha-services/version.rb
- lib/services/trello/trello_board_resource.rb
found_resource can be `nil` in some case (https://sentry.io/aha-labs-inc/aha-production/issues/303066013/).
Coercing to an array keeps the existing functionilty, but protects
against nil.
> APP-4677: Fix nil found_resource for trello board resource

- Gemfile.lock
- lib/aha-services/version.rb
- lib/services/github_issues.rb
- spec/services/github_issues_spec.rb
Currently if someone sets up the integration webhook on the wrong repo,
the integration tries to link with that wrong repo's issues to Aha!
features. This adds a check to ensure we only accept from the right
source.
> Adjusts github integration to only accept payloads from intended repo.

- Gemfile
- Gemfile.lock
- Procfile
- README.md
- config.ru
- lib/proxy/server.rb
Set up a procfile, config.ru, and tweak the proxy server to allow
running easily on Heroku for users who want to use custom code but do
not want to stand up a server to handle it.
> Allow running on heroku

- spec/fixtures/update_feature_event.json
- spec/services/trello_spec.rb
Fixes #115 
Includes:
1. Update part of the feature now exercises the update path
2. Refactored to stub requests in one place (removed duplication)
3. Fixed logic in update spec to do what the comments indicated (checking for pre-existing attachment)
> Fix trello spec (inc. exercise update path)

- Gemfile.lock
- lib/aha-services/version.rb
- lib/services/gitlab/gitlab_resource.rb
- lib/services/gitlab_issues.rb
- spec/services/gitlab_issues_spec.rb
In gitlab, you can create groups that namespace the report. So I could have
aha-app/docs and jjbohn/docs. Our current implementation only showed the repo
name, not the group, so it would just show "doc" twice. This actually made
it impossible to tie it to the correct report as well since we use the name
to map the integration.
This fix shows the full name now and fixes both issues. The problem was that we were using `name` from the API. That never contains the namespace, we need to be using `path_with_namespace`.
It is also backwards compatible. To do this, it checks if the saved
repo name is the full name, or just the repo name, then acts accordingly.
**Before:**
**After:**
> Show the full name for gitlab repos

- lib/aha-services/version.rb
- lib/services/github_issues.rb
- spec/services/github_issues_spec.rb
Dearest Reviewer
Do not listen to the opened action when setting tags. They are not
there yet.
Changes
Do not sync tags for the open action
When sending and it is a create always send the open status
Becker
> github-should-ignore-open-actions

- lib/aha-services/version.rb
- lib/services/github_issues.rb
If we don't send the tags immediately, and they have a webhook set up, it is possible for the initial creation to trigger a webhook which clears the tags in aha
https://big.aha.io/features/APP-5806
> Send tags to GitHub on initial issue creation.

- lib/aha-services/version.rb
- lib/services/github_issues.rb
- spec/services/github_issues_spec.rb
The internet is to picky when it comes to locations..
Changes
Consolidate url generation in github
I did not use URI.join like I wanted to because it does not work
like you want it to. Splits and joins seemed the best bet.
Becker
> prevent-double-slash-in-github-url

- lib/aha-services/version.rb
- lib/services/github_issues.rb
- spec/services/github_issues_spec.rb
It turns out that github returns a number for the issue id and not
a string. I am not sure what math we will do with the id but when
generating urls we dont care.
Changes:
Adds a to_s to the paths the code builds out
Adds a test
Bumped version number
Becker
> allow-numbers-in-github-urls

- Gemfile.lock
- lib/aha-services/version.rb
- lib/services/jira/jira_mapped_fields.rb
There is a case where `[nil]` is sent to the services gem. when converted, this becomes `[null]`. This causes JIRA to blow up, and syncing to break.
> compacting out nil values from lists in jira sync

- Gemfile
- Gemfile.lock
- README.md
- lib/services/github_issues.rb
- spec/services/github_issues_spec.rb
GitHub issues *always* are created as opened. When existing features are sent to create new issues in GitHub, they always immediately propagate back to Aha! in webhooks, overriding feature statuses, if they were anything other than whatever workflow status was mapped to 'open'.
This flags issues being created from Aha! so that when we receive the corresponding "opened" webhooks, we know whom to defer to for the authoritative source of truth about the current status of the item.
Feature: [APP-6404](https://big.aha.io/features/APP-6404)
> APP-6404: Treat sent-from-Aha! GitHub issues specially

- lib/aha-services/version.rb
- lib/services/gitlab_issues.rb
support ticket: https://ahasupport.zendesk.com/agent/tickets/194756
Gitlab may have changed the string that they are sending. It seems like "opened" is being used rather than "reopened", when an issue is reopened. So we just check for either.
> Update feature state when issue is reopened

- lib/services/tfs/tfs_requirement_mapping_resource.rb
This can be nil but the code doesn't reflect that and would error if that was the case.
> Handle nil requirement relations

- docs/google_hangouts_chat.md
- lib/services/flowdock.rb
- lib/services/google_hangouts_chat.rb
- lib/services/hip_chat.rb
- spec/services/google_hangouts_chat_spec.rb
Adds support for an integration with google hangouts chat. We use audit records in Aha! to populate card fields in a google hangouts chat room. It works basically the same way that the slack activity feed integration does.
> App 6984 google hangouts chat

- lib/services/fogbugz/fogbugz_resource.rb
Fogbugz sends html for a missing account which we can not parse.
Changes
Catch xml parse errors
add an account message along side a general message
Becker
> PF-53-56-catch-bad-xml

- lib/services/jira/jira_user_resource.rb
Description
-----------
User lookup needs to pick the best matched result, not the first one.
Implementation is copied directly from aha-services-2.
[Aha! feature/requirement](https://big.aha.io/features/IM-377)
Peer review checklist
---------------------
> IM-377 Backport implementation of Jira user lookup from aha-services-2

- lib/services/common/color_converter.rb
- lib/services/common/markdown_table_converter.rb
- lib/services/jira/jira_wiki_converter.rb
- spec/services/jira/jira_wiki_converter_spec.rb
- Support tables with colspan
- Support text foreground and background colors
> IM-419: Port html-to-jira formatter changes from aha-services-2

- lib/services/bitbucket_commit_hook.rb
- spec/fixtures/bitbucket_commit_hook/bitbucket_commit_hook_webhook_numbers.json
- spec/services/bitbucket_webhook_spec.rb
Previously, the regex for the bitbucket commit hook assumed that product prefixes did not have numbers in them. Now the pattern allows for prefixes with numbers!
> Bitbucket commit hooks should process product prefixes with numbers in them

- lib/services/microsoft_teams.rb
When users select the Aha! connector in Microsoft teams, and use that webhook to connect to our Teams connector, they get this error. Our Teams integration connects to their webhook connector. Their Aha! connector connects to our webhook integration. This is confusing, and this tells the user what's going on rather than telling them that there's an unhandled error.
> telling users when they're using the wrong connector

- lib/services/bitbucket_commit_hook.rb
- spec/fixtures/bitbucket_commit_hook/bitbucket_commit_hook_no_email.json
- spec/services/bitbucket_webhook_spec.rb
There is an issue where a Bitbucket user can not have an email configured so the author field comes through with no email. This causes `Mail::Address` to raise an exception and fails the comment posting process. Since the email address is used as an identifier at best, there's no reason we can't just use the raw string if we can't break it out into a display name and email.
> Correctly process bitbucket webhooks without author emails

- lib/aha-services.rb
- lib/services/jira/jira_resource.rb
- spec/services/jira/jira_resource_spec.rb
As part of Atlassian's GDPR compliance effort, there are several changes that affect the way that Jira Connect integrations authenticate with the remote server ([Connect app migration guide](https://developer.atlassian.com/cloud/jira/platform/connect-app-migration-guide/#migrating-existing-app)). Specifically:
- the `user_id` and `user_key` params are being removed
- the `user` section of the JWT `context` claim is being removed
- the user must be identified in the `sub` claim of the JWT payload, using a namespaced urn that identifies the value as either an Atlassian account ID (preferred) or user key (deprecated, to be removed soon)
> PF-366-1: Jira Connect GDPR changes

- lib/services/jira.rb
- spec/services/jira_spec.rb
It appears that Jira's `POST /api/2/issue` endpoint recently (sometime over the weekend) changed to only accept the user `accountId` to identify the issue reporter and assignee, whereas previously, it would accept either the user `name` or the user `accountId`. We still need to support user `name` (without the `accountId`) for on-prem instances.
This is part of the [Atlassian GDPR changes](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/#issue).
> PF-420: Use the Jira user account ID for reporter/assignee

- lib/services/jira/jira_wiki_converter.rb
- spec/services/jira/jira_wiki_converter_spec.rb
To get checklists to appear correctly in HTML and emails, we need to
add an element with a unicode checkbox. When sending the HTML to Jira,
we replace checklists with images. In those cases, we want to ignore
the other checkboxes.
> APPS-226: Ignore unicode checkboxes in checklists

- lib/services/gitlab_issues.rb
Has better table support.
Before
After
GitLab flavored markdown is advertised as a superset of GitHub flavored markdown, so there shouldn't be a problem with any of the other syntax conversion. https://gitlab.com/gitlab-org/gitlab-foss/issues/52391
> PF-642: Use GitHub markdown converter for GitLab

- lib/services/jira/jira_mapped_fields.rb
Integrations 2.0 has been changed to use the name field instead of the key field, but for v1 only the assignee field was updated also update custom fields.
> Use name not key for jira fields

- lib/services/slack.rb
Handle the case where Slack may return `invalid_token` which we attempt to parse as JSON and error.
> Fixes IM-1226 - Handle invalid_token error thrown by Slack.

- Gemfile
- lib/services/microsoft_teams.rb
We were throwing an error when the response only contained `Connector configuration not found` because we were trying to parse this as if it was JSON.
> Fixes IM-1225 - Handle 'Connector configuration not found' error.

- aha-services.gemspec
- lib/aha-services.rb
Disable warnings about shadowing keys. 
It turns out that Hashie::Mash has always shadowed keys, the warning is new.
> PF-1011 We need a newer hashie gem to support omniauth-github.

- lib/aha-services/helpers.rb
- spec/lib/aha-services/helpers_spec.rb
Single newlines are being stripped from description text coming from PivotalTracker. They should be converted to `<br>` instead to preserver the original formatting, otherwise adjacent lines are merged together.
Double newlines are correctly translated into paragraph tags, so this change does not affect those.
Changes: convert single newlines to `<br>` in description text
* [Support ticket](https://ahasupport.zendesk.com/agent/tickets/569855)
> PFT-30: Fix PivotalTracker description formatting

- aha-services.gemspec
This pr is to remove the upper bound on the activesupport gem
Changes
remove the version in the spec file.
Becker
> Remove rails upper bound

- lib/aha-services/helpers.rb
- spec/lib/aha-services/helpers_spec.rb
This handles a string line `Line 1  \nLine 2` not rendering to HTML as `<p>Line 1<br><br>Line 2</p>` with duplicate line break elements.
> DEVOPS-479: handle lines with trailing whitespace in markdown to html conversion

- lib/services/pivotal_tracker.rb
- lib/services/pivotal_tracker/pivotal_tracker_feature_and_requirement_mapping_resource.rb
We do not support initiatives in the pivotal integration, but we have included it as an option in the settings. Removing it as the only customer to ever use it so far is in a trial. We should just put the effort towards making a v2 integration.
* [Support ticket](https://ahasupport.zendesk.com/agent/tickets/593950)
> A-11529: Pivotal V1 integration does not support initiatives

- lib/services/jira/jira_resource.rb
- spec/services/jira/jira_resource_spec.rb
During the Ruby 3 upgrade, we changed how the auth headers were added in several integrations. The change made to the Jira moved the code into a method that was being overridden by a method further down in the class. We need to move the auth code into that method for it to run.
> DEVELOP-1246: Fix basic auth on v1 Jira integrations

- spec/fixtures/update_feature_event.json
An eagle-eyed customer noticed that the `event` on an eight year old fixture in `aha-services` is incorrect. It's also incorrect in `aha-services-2`.
Changes: Fix fixture
* [Support ticket](https://ahasupport.zendesk.com/agent/tickets/814022)
> DEVOPS-1683: Fix services fixtures

- lib/services/gitlab_issues.rb
Newer GitLab versions use a new URL format with a spot in the URL for project subgroups. Our integration uses the older format, however, which results in broken integration links. This patch updates the integration to use the web URL as reported by the server which will use whichever URL format it uses (and also will account for populated subgroups, if one exists). This should support past, present, and future GitLab servers as both the current v4 API includes this field as well as the much older v3 API.
Ref: https://gitlab.com/gitlab-org/gitlab/-/issues/214217
> DEVOPS-1932: fix gitlab integration issue links not using the newer subgroup format

- docs/zendesk.md
- lib/aha-services/schema.rb
- lib/services/zendesk.rb
DO NOT MERGE Depends on https://github.com/aha-app/aha-app/pull/27013
Adds a `ideas_portals` field that can be used to render a list of ideas portals to associate to the extension.
* [Aha! feature](https://big.aha.io/features/AI-1015)
> Add  to possible extension fields

- lib/services/gitlab_issues.rb
Some gitlab projects have prefixes which cause the `get_project` method to not return the correct project.
In these cases, we can additionally check the `path_with_namespace` to find a project ending with the data.project.
> Allow gitlab projects to be found by the suffix

- lib/services/slack.rb
- lib/services/slack_commands.rb
[Aha Feature](https://big.aha.io/features/A-17023)
As part of the update to our Slack application, we need to rename our existing application so they are not "Slack [From Aha!]" as Slack is very strict about it. Instead we have to use something like "Aha! (To Slack)"
> A-17023 Update the slack names
